<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.0</version>
        <relativePath/>
    </parent>

    <groupId>com.saltatorv</groupId>
    <artifactId>notification-manager</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>notification-manager</name>
    <description>notification-manager</description>

    <url/>

    <developers>
        <developer>
            <name>SaltatorV</name>
            <roles>
                <role>Developer</role>
            </roles>
        </developer>
    </developers>

    <modules>
        <module>notification-manager-domain</module>
        <module>notification-manager-application</module>
        <module>notification-manager-infrastructure</module>
        <module>notification-manager-container</module>
    </modules>

    <properties>
        <!-- CORE -->
        <java.version>17</java.version>

        <!-- NOTIFICATION-MANAGER -->
        <notification-manager-domain.version>0.0.1-SNAPSHOT</notification-manager-domain.version>
        <notification-manager-application.version>0.0.1-SNAPSHOT</notification-manager-application.version>
        <notification-manager-infrastructure.version>0.0.1-SNAPSHOT</notification-manager-infrastructure.version>

        <!-- AVRO -->
        <avro-compiler.version>1.12.1</avro-compiler.version>
        <avro-maven-plugin.version>1.12.1</avro-maven-plugin.version>

        <!-- JAKARTA -->
        <jakarta.annotation-api.version>3.0.0</jakarta.annotation-api.version>

        <!-- TESTING -->
        <junit-jupiter.version>5.14.1</junit-jupiter.version>

        <pitest.version>1.22.0</pitest.version>
        <pitest-junit5-plugin.version>1.2.3</pitest-junit5-plugin.version>

        <jacoco.version>0.8.12</jacoco.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- SPRING -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter</artifactId>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-test</artifactId>
                <scope>test</scope>
            </dependency>

            <!-- NOTIFICATION-MANAGER -->
            <dependency>
                <groupId>com.saltatorv</groupId>
                <artifactId>notification-manager-domain</artifactId>
                <version>${notification-manager-domain.version}</version>
            </dependency>
            <dependency>
                <groupId>com.saltatorv</groupId>
                <artifactId>notification-manager-application</artifactId>
                <version>${notification-manager-application.version}</version>
            </dependency>
            <dependency>
                <groupId>com.saltatorv</groupId>
                <artifactId>notification-manager-infrastructure</artifactId>
                <version>${notification-manager-infrastructure.version}</version>
            </dependency>

            <!-- AVRO -->
            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-compiler</artifactId>
                <version>${avro-compiler.version}</version>
            </dependency>


            <!-- JAKARTA -->
            <dependency>
                <groupId>jakarta.annotation</groupId>
                <artifactId>jakarta.annotation-api</artifactId>
                <version>${jakarta.annotation-api.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- TESTING -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-maven</artifactId>
            <version>${pitest.version}</version>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <!-- AVRO -->
                <plugin>
                    <groupId>org.apache.avro</groupId>
                    <artifactId>avro-maven-plugin</artifactId>
                    <version>${avro-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
