<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.saltatorv</groupId>
        <artifactId>notification-manager</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>notification-manager-domain</artifactId>
    <packaging>jar</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>${pitest.version}</version>
                <executions>
                    <execution>
                        <id>pit-report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <targetClasses>
                        <param>com.saltatorv.notification.manager.domain*</param>
                    </targetClasses>
                    <targetTests>
                        <param>com.saltatorv.notification.manager.domain*</param>
                    </targetTests>
                    <excludedMethods>
                        <excludedMethod>equals</excludedMethod>
                        <excludedMethod>hashCode</excludedMethod>
                        <excludedMethod>toString</excludedMethod>
                        <excludedMethod>get*</excludedMethod>
                    </excludedMethods>
                    <mutators>
                        <mutator>STRONGER</mutator>
                    </mutators>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>${pitest-junit5-plugin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

</project>
