{
  "type": "record",
  "name": "SendSystemNotificationCommand",
  "namespace": "com.saltatorv.notification.manager.infrastructure.avro.notification.system",
  "doc": "",
  "fields": [
    {
      "name": "metadata",
      "type": "com.saltatorv.notification.manager.infrastructure.avro.shared.CommonMetadata"
    },
    {
      "name": "userId",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      },
      "doc": "Unique identifier of the user within the system."
    },
    {
      "name": "message",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      },
      "doc": "Message content to be delivered",
      "minLength": 2,
      "maxLength": 512
    }
  ]
}